version: '3.8'

services:
  idcard:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./result_detection:/app/result_detection/
    command: sh -c "uvicorn run:app --host 0.0.0.0 --port 8000"

    restart: always