cropper:
    cfg: /app/weights/cropper/yolov4_tiny.cfg
    weight: /app/weights/cropper/yolov4_tiny_final.weights

detector:
    cfg: /app/weights/detector/yolotinyv4_cccd.cfg
    weight: /app/weights/detector/yolotinyv4_cccd_final.weights

reader:
    weight: /app/weights/reader/transformerocr.pth

key_api: '4ed73f45cc4c08c57be44ad25221093d'

save_image: True